spring.application.name=demo
spring.datasource.initialization-mode=always
springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.enabled=true

spring.datasource.url=jdbc:postgresql://db:5432/tenpoDB
spring.datasource.username=tenpo1
spring.datasource.password=tenpo1*
spring.jpa.hibernate.ddl-auto=update


external.percentage.url=http://app:8080/external/percentage
external.percentage.value=0.2


